import type { CatalogCategoryDto, CatalogProductDto } from '../types/catalog.js';

type FixtureProduct = CatalogProductDto & {
  categorySlug: string;
};

const defaultPlacements = (code = 'default') => [
  {
    code,
    displayName: code === 'front' ? 'Front print' : 'Default print area',
    technique: 'dtg',
    isDefault: true,
  },
];

export const sampleCatalog: {
  categories: CatalogCategoryDto[];
  products: FixtureProduct[];
} = {
  categories: [
    {
      id: 'fixture-category-apparel',
      title: 'Apparel',
      slug: 'apparel',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-hats',
      title: 'Hats',
      slug: 'hats',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-drinkware',
      title: 'Drinkware',
      slug: 'drinkware',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-wall-art',
      title: 'Wall art',
      slug: 'wall-art',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-bags',
      title: 'Bags',
      slug: 'bags',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-stickers',
      title: 'Stickers',
      slug: 'stickers',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-phone-cases',
      title: 'Phone cases',
      slug: 'phone-cases',
      imageUrl: null,
      isLaunchCategory: true,
    },
    {
      id: 'fixture-category-stationery',
      title: 'Stationery',
      slug: 'stationery',
      imageUrl: null,
      isLaunchCategory: true,
    },
  ],
  products: [
    {
      id: 'fixture-product-heavyweight-shirt',
      title: 'Heavyweight cotton shirt',
      slug: 'heavyweight-cotton-shirt',
      type: 'apparel',
      brand: 'Fixture',
      description: 'A durable everyday garment for artwork, logos, and campaign drops.',
      thumbnailUrl: null,
      categorySlug: 'apparel',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-shirt-black-m',
          name: 'Black / M',
          size: 'M',
          color: 'Black',
          colorCode: '#111827',
          imageUrl: null,
          isAvailable: true,
          costCents: 1450,
        },
        {
          id: 'fixture-variant-shirt-white-l',
          name: 'White / L',
          size: 'L',
          color: 'White',
          colorCode: '#f8fafc',
          imageUrl: null,
          isAvailable: true,
          costCents: 1450,
        },
      ],
      placements: [
        {
          code: 'front',
          displayName: 'Front print',
          technique: 'dtg',
          isDefault: true,
          width: 12,
          height: 16,
        },
        {
          code: 'back',
          displayName: 'Back print',
          technique: 'dtg',
          isDefault: false,
          width: 12,
          height: 16,
        },
      ],
    },
    {
      id: 'fixture-product-embroidered-cap',
      title: 'Structured embroidered cap',
      slug: 'structured-embroidered-cap',
      type: 'hat',
      brand: 'Fixture',
      description: 'A front-panel cap for compact marks, badges, and short text.',
      thumbnailUrl: null,
      categorySlug: 'hats',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-cap-navy',
          name: 'Navy',
          color: 'Navy',
          colorCode: '#172554',
          imageUrl: null,
          isAvailable: true,
          costCents: 1275,
        },
      ],
      placements: [
        {
          code: 'embroidery_front',
          displayName: 'Front embroidery',
          technique: 'embroidery',
          isDefault: true,
          width: 4,
          height: 2,
        },
      ],
    },
    {
      id: 'fixture-product-ceramic-mug',
      title: 'Ceramic mug',
      slug: 'ceramic-mug',
      type: 'drinkware',
      brand: 'Fixture',
      description: 'A wrap-ready mug for gifts, desk drops, and small batch launches.',
      thumbnailUrl: null,
      categorySlug: 'drinkware',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-mug-white-11oz',
          name: 'White / 11 oz',
          size: '11 oz',
          color: 'White',
          colorCode: '#ffffff',
          imageUrl: null,
          isAvailable: true,
          costCents: 830,
        },
      ],
      placements: defaultPlacements(),
    },
    {
      id: 'fixture-product-matte-poster',
      title: 'Matte poster',
      slug: 'matte-poster',
      type: 'wall-art',
      brand: 'Fixture',
      description: 'A lightweight wall art option for posters, prints, and event graphics.',
      thumbnailUrl: null,
      categorySlug: 'wall-art',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-poster-12x18',
          name: '12 x 18 in',
          size: '12 x 18',
          imageUrl: null,
          isAvailable: true,
          costCents: 700,
        },
      ],
      placements: defaultPlacements(),
    },
    {
      id: 'fixture-product-tote',
      title: 'Canvas tote bag',
      slug: 'canvas-tote-bag',
      type: 'bag',
      brand: 'Fixture',
      description: 'A useful merch staple with a large single-sided print area.',
      thumbnailUrl: null,
      categorySlug: 'bags',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-tote-natural',
          name: 'Natural',
          color: 'Natural',
          colorCode: '#d6c3a3',
          imageUrl: null,
          isAvailable: true,
          costCents: 1125,
        },
      ],
      placements: defaultPlacements('front'),
    },
    {
      id: 'fixture-product-vinyl-sticker',
      title: 'Kiss-cut sticker',
      slug: 'kiss-cut-sticker',
      type: 'sticker',
      brand: 'Fixture',
      description: 'A compact add-on product for logos, mascots, and campaign art.',
      thumbnailUrl: null,
      categorySlug: 'stickers',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-sticker-3x3',
          name: '3 x 3 in',
          size: '3 x 3',
          imageUrl: null,
          isAvailable: true,
          costCents: 250,
        },
      ],
      placements: defaultPlacements(),
    },
    {
      id: 'fixture-product-phone-case',
      title: 'Slim phone case',
      slug: 'slim-phone-case',
      type: 'phone-case',
      brand: 'Fixture',
      description: 'A protective case format for device-specific artwork.',
      thumbnailUrl: null,
      categorySlug: 'phone-cases',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-phone-case-iphone',
          name: 'iPhone compatible',
          imageUrl: null,
          isAvailable: true,
          costCents: 1025,
        },
      ],
      placements: defaultPlacements(),
    },
    {
      id: 'fixture-product-notebook',
      title: 'Spiral notebook',
      slug: 'spiral-notebook',
      type: 'stationery',
      brand: 'Fixture',
      description: 'A notebook surface for cover art, office gifts, and creator bundles.',
      thumbnailUrl: null,
      categorySlug: 'stationery',
      isSellable: true,
      variants: [
        {
          id: 'fixture-variant-notebook-ruled',
          name: 'Ruled pages',
          imageUrl: null,
          isAvailable: true,
          costCents: 900,
        },
      ],
      placements: defaultPlacements(),
    },
  ],
};
