import { readFileSync } from "node:fs";
import prettier from "prettier";

export { validateMerchantConfig } from "../packages/merchant-profile/merchant-validation.mjs";

export function readMerchantConfig(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    throw new Error(
      "Merchant configuration is missing, unreadable, or invalid JSON.",
    );
  }
}

/** Produces the same immutable typed module for browser and server consumers. */
export async function renderMerchantConfigModule(config) {
  const source = `// Generated by npm run config:generate. Edit config/merchant.config.json instead.\n\nexport const merchantConfig = ${JSON.stringify(config, null, 2)} as const;\n\nexport type MerchantConfig = typeof merchantConfig;\n`;
  // Keep this explicit because the same source is emitted beneath two workspace-local
  // Prettier roots. Generation must not vary with the caller's current directory.
  return prettier.format(source, {
    parser: "typescript",
    semi: true,
    trailingComma: "es5",
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    arrowParens: "always",
  });
}
