import { readFileSync, realpathSync } from "node:fs";
import { resolve, sep } from "node:path";
import prettier from "prettier";

export { policyPaths, policyDigest, validatePolicyContent } from "../packages/merchant-profile/policy-validation.mjs";

/** Public committed JSON only: prevent traversal and symlink escape, and never echo file contents. */
export function readPolicyContent(
  merchant,
  configDirectory = resolve("config"),
) {
  try {
    if (
      !/^policies\/[a-z0-9][a-z0-9.-]*\.json$/.test(
        merchant.policies.contentFile,
      )
    )
      throw new Error();
    const root = resolve(realpathSync(configDirectory), "policies");
    const path = realpathSync(
      resolve(configDirectory, merchant.policies.contentFile),
    );
    if (!path.startsWith(root + sep)) throw new Error();
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    throw new Error(
      "Policy content is missing, unreadable, invalid JSON, or outside config/policies.",
    );
  }
}

export function assertPolicyBuildMode(document, source = process.env) {
  if (document.purpose !== "fixture-only") return;
  // An opt-in alone cannot turn demonstration notices into deployable commerce policies.
  const allowed =
    source.OMS_POLICY_FIXTURE_REHEARSAL === "1" &&
    source.VITE_PUBLIC_APP_MODE === "oss" &&
    source.CHECKOUT_ACCESS_MODE === "closed";
  const liveKeys = [
    "ALLOW_LIVE_PAYMENTS",
    "ALLOW_LIVE_FULFILLMENT",
    "PRINTFUL_AUTO_CONFIRM_ORDERS",
    "ENABLE_LIVE_OPENAI",
    "ENABLE_LIVE_STRIPE",
    "ENABLE_LIVE_PRINTFUL",
    "FULFILLMENT_ENABLED",
    "TRANSACTIONAL_EMAILS_ENABLED",
    "VITE_ENABLE_PUBLIC_CHECKOUT",
  ];
  if (
    !allowed ||
    liveKeys.some((key) => source[key] !== "false") ||
    source.VERCEL
  )
    throw new Error(
      "Fixture-only policies require the isolated no-provider rehearsal environment; they cannot be deployed.",
    );
}

export async function renderPolicyModule(document, metadataOnly = false) {
  const { pages, ...approval } = document;
  return prettier.format(
    `// Generated by config:generate. Operator-owned prose is in config/policies.\nexport const policyApproval = ${JSON.stringify(approval)} as const;\n${metadataOnly ? "" : `export const policyPages = ${JSON.stringify(pages)} as const;\n`}`,
    {
      parser: "typescript",
      singleQuote: true,
      printWidth: 100,
      trailingComma: "es5",
    },
  );
}
